VIRTUAL_WARDS_STATS_HOMEPAGE_URL: "https://www.england.nhs.uk/statistics/statistical-work-areas/virtual-ward/"
VIRTUAL_WARDS_INFO_URL: "https://www.england.nhs.uk/virtual-wards/"
GP_POPULATION_URL: "https://digital.nhs.uk/data-and-information/publications/statistical/patients-registered-at-a-gp-practice"
GITHUB_URL: "https://github.com/alarthast/virtual-wards-statistics/tree/main"

DATA_FILENAME: "virtual_ward_statistics.csv"
COLUMN_NAMES:
  Region : region
  Region Code : region_code
  ICB code : icb_code
  Name : name
  Virtual Ward Capacity : capacity
  Virtual Ward Capacity per 100,000 GP registered population aged 16 years and over : capacity_per_population
  GP registered population aged 16 and over : population
  Patients in a Virtual Ward : num_ward_patients
  Occupancy % : occupancy

GEOJSON_FILENAME: "ICB_JUL_2022_EN_BUC_V3_5138400207907180607.geojson"
ICB_CODE_LOOKUP_FILENAME: "ICB_JUL_2022_EN_NC.xlsx"

HEADER: "NHS Virtual Wards Statistics"

MAP_CENTRE:
  lat: 53
  lon: -2

DROPDOWN_OPTIONS:
  capacity: "Virtual Ward Capacity (see note 1)"
  capacity_per_population: "Virtual Ward Capacity per 100,000 GP registered population aged 16 years and over (see note 2)"
  num_ward_patients: "Patients in a Virtual Ward (see notes 1 and 3)"
  occupancy: "Occupancy % (see note 4)"

FORMATTERS:
  capacity: ":.0f"
  capacity_per_population: ".1f"
  num_ward_patients: ".0f"
  occupancy: ".1%"

NHS_COLOURS:
  BLUE: "#005EB8"
  DARK_BLUE: "#003087"
  BRIGHT_BLUE: "#0072CE"
  LIGHT_BLUE: "#41B6E6"
  AQUA_BLUE: "#00A9CE"